# For more info on HTTP files go to https://aka.ms/vs/httpfile

@HostAddress = https://localhost:6020

### Get Random Number (default range 0-100)
POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json
MCP-Protocol-Version: 2025-11-25

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "tools/call",
    "params": {
        "name": "get_random_number",
        "arguments": {
            "min": 1,
            "max": 100
        }
    }
}

### Get All Products via MCP
POST {{HostAddress}}/
Accept: application/json, text/event-stream
Content-Type: application/json
MCP-Protocol-Version: 2025-11-25

{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/call",
    "params": {
        "name": "get_products_async"
    }
}

### Get Products directly from API
GET {{HostAddress}}/api/products
Accept: application/json

````````


# Response
